import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#0B7EC8",
    },
    header: {
        backgroundColor: "#0B7EC8",
        paddingBottom: 25,
        paddingTop: 20,
    },
    headerContent: {
        paddingHorizontal: 25,
        paddingTop: 15,
    },
    headerTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 25,
        position: "relative",
    },
    logoContainer: {
        position: "absolute",
        left: 0,
        right: 0,
        alignItems: "center",
        zIndex: 1,
        paddingTop: 20
    },
    logoText: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#FFFFFF",
        letterSpacing: 2,
    },
    logoutButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.3)",
        zIndex: 2,
    },
    logoutText: {
        fontSize: 12,
        color: "#FFFFFF",
        fontWeight: "600",
        marginLeft: 6,
        letterSpacing: 0.5,
    },
    userInfo: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 20,
    },
    userAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: "#FFFFFF",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 18,
    },
    userName: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#FFFFFF",
        marginBottom: 4,
    },
    userRole: {
        fontSize: 14,
        color: "#E3F2FD",
        letterSpacing: 0.5,
    },
    userIdContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 25,
    },
    userIdLabel: {
        fontSize: 12,
        color: "#E3F2FD",
        marginLeft: 6,
        marginRight: 10,
    },
    userId: {
        fontSize: 14,
        color: "#FFFFFF",
        fontWeight: "500",
        flex: 1,
    },
    mainContent: {
        flex: 1,
        padding: 25,
        backgroundColor: "#F5F5F5",
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        marginTop: -15,
    },
    cardRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 25,
    },
    cardRowCenter: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 25,
    },
    card: {
        flex: 1,
        aspectRatio: 1,
        borderRadius: 16,
        padding: 25,
        alignItems: "center",
        justifyContent: "center",
        marginHorizontal: 10,
        elevation: 6,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.12,
        shadowRadius: 4.5,
    },
    cardText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#333",
        textAlign: "center",
        marginTop: 12,
        lineHeight: 18,
    },
});